services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: redestore
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - redestore-db:/var/lib/postgresql/data

volumes:
  redestore-db:
